import os
import google.generativeai as genai

genai.configure(api_key=os.environ["GEMINI_API_KEY"])
model = genai.GenerativeModel("gemini-1.5-flash")


def get_gemini_response(text):
    """
    Function that sends text to Gemini and returns its response
    
    Args:
        text (str): The text to send to Gemini
        
    Returns:
        str: The response generated by Gemini
    """
    response = model.generate_content(text)
    #print(f"Total tokens for Gemini: {response.usage_metadata.total_token_count}")
    return response.text
