from mistralai import Mistral
import os


api_key = os.environ["MISTRALAI_API_KEY"]
model = "mistral-large-latest"

client = Mistral(api_key=api_key)

def get_mistral_response(text):
    """
    Function that sends text to MistraAi and returns its response
    
    Args:
        text (str): The text to send to Gemini
        
    Returns:
        str: The response generated by MistralAI
    """

    
    chat_response = client.chat.complete(
        model = model,
        messages = [
            {
                "role": "user",
                "content": text,
            },
        ]
    )

    #print(f"Number of MistralAI tokens: {chat_response.usage.total_tokens}")
    return chat_response.choices[0].message.content
